CREATE TABLE member
(
    id         NUMBER PRIMARY KEY,
    email      VARCHAR2(100) UNIQUE NOT NULL,
    password   VARCHAR2(255) NOT NULL,
    nickname   VARCHAR2(50) NOT NULL,
    role       VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    created_at DATE DEFAULT SYSDATE,

    -- role CHECK 제약 추가
    CONSTRAINT CHK_MEMBER_ROLE CHECK (role IN ('USER', 'ADMIN'))
);

CREATE SEQUENCE member_seq
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;