-- SEQUENCE
CREATE SEQUENCE REVIEW_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE REVIEW_IMAGE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 1. REVIEW
CREATE TABLE REVIEW
(
    id                  NUMBER PRIMARY KEY,
    restaurant_id       NUMBER NOT NULL,
    member_id           NUMBER NOT NULL,
    rating              NUMBER(1) NOT NULL,
    content             VARCHAR2(1000),
    revisit             CHAR(1)   DEFAULT 'N',
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP,
    verification_status CHAR(1)   DEFAULT 'N',
    receipt_url         VARCHAR2(500),
    like_count          NUMBER    DEFAULT 0,
    helpful_count       NUMBER    DEFAULT 0,

    CONSTRAINT CHK_REVIEW_RATING CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT CHK_REVIEW_REVISIT CHECK (revisit IN ('Y', 'N')),
    CONSTRAINT CHK_REVIEW_VERIFY CHECK (verification_status IN ('N', 'A', 'R')),

    -- ON DELETE CASCADE 추가 맛집 or 회원 삭제시 리뷰 데이터 삭제 되게.
    CONSTRAINT FK_REVIEW_RESTAURANT FOREIGN KEY (restaurant_id)
        REFERENCES RESTAURANT (id) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_MEMBER FOREIGN KEY (member_id)
        REFERENCES MEMBER (id) ON DELETE CASCADE,

    CONSTRAINT UK_REVIEW_MEMBER_RESTAURANT UNIQUE (restaurant_id, member_id)
);

-- 2. REVIEW_IMAGE
CREATE TABLE REVIEW_IMAGE
(
    id        NUMBER PRIMARY KEY,
    review_id NUMBER NOT NULL,
    image_url VARCHAR2(500) NOT NULL,

    CONSTRAINT FK_REVIEW_IMAGE_REVIEW FOREIGN KEY (review_id)
        REFERENCES REVIEW (id) ON DELETE CASCADE
);

-- 3. REVIEW_SITUATION
CREATE TABLE REVIEW_SITUATION
(
    review_id NUMBER NOT NULL,
    situation VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_REVIEW_SITUATION PRIMARY KEY (review_id, situation),
    CONSTRAINT FK_REVIEW_SIT_REVIEW FOREIGN KEY (review_id)
        REFERENCES REVIEW (id) ON DELETE CASCADE
);

-- 4. REVIEW_LIKE
CREATE TABLE REVIEW_LIKE
(
    review_id  NUMBER,
    member_id  NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_REVIEW_LIKE PRIMARY KEY (review_id, member_id),
    -- ON DELETE CASCADE 추가
    CONSTRAINT FK_LIKE_REVIEW FOREIGN KEY (review_id)
        REFERENCES REVIEW (id) ON DELETE CASCADE,
    CONSTRAINT FK_LIKE_MEMBER FOREIGN KEY (member_id)
        REFERENCES MEMBER (id) ON DELETE CASCADE
);

-- 5. REVIEW_HELPFUL
CREATE TABLE REVIEW_HELPFUL
(
    review_id  NUMBER,
    member_id  NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_REVIEW_HELPFUL PRIMARY KEY (review_id, member_id),
    -- ON DELETE CASCADE 추가
    CONSTRAINT FK_HELPFUL_REVIEW FOREIGN KEY (review_id)
        REFERENCES REVIEW (id) ON DELETE CASCADE,
    CONSTRAINT FK_HELPFUL_MEMBER FOREIGN KEY (member_id)
        REFERENCES MEMBER (id) ON DELETE CASCADE
);